### PR TITLE
[CoW Protocol] Add Raven solver

### PR DESCRIPTION
**Pull request by harisang**
This PR adds the Raven solver to the CoW Protocol solver competition

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
Wonderful!

**Comment by harisang** [comment]
cc @jeff-dude

**Comment by bh2smith** [comment]
It looks like I might actually be able to merge this... although I don't know if there is anything on their backend that needs to be handled...

**Comment by jeff-dude** [comment]
unfortunately all v1 engine objects require manual intervention on the backend. i'll try to get to open PRs today / tomorrow

**Review by jeff-dude — APPROVED** [review]
should be set 🤝

**Pull request merged**
