### PR TITLE
[CoW Protocol] Add Barter Solver

### PR DESCRIPTION
**Pull request by harisang**
This PR adds the Barter solver (prod & staging) to the solver competition.

### CODE REVIEW

**Comment by harisang** [comment]
cc @jeff-dude @bh2smith

**Review by bh2smith — APPROVED** [review]

**Review by jeff-dude — APPROVED** [review]
should be updated 👍

**Comment by bh2smith** [comment]
reported this account for spam.

**Comment by jeff-dude** [comment]
> reported this account for spam.

thank you, they're blocked on spellbook too

**Pull request merged**
